require("config.autosave")
require("config.bufferline")
require("config.colorizer")
require("config.nvim-comment")
require("config.tree-sitter")
require("config.nvim-lsp-installer")
require("config.lspkind")
require("config.lspconfig")
